version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: friday
      time: "08:00"
    labels:
      - "dependencies"
